import { CoverageResult } from '../types';
import {
  groupByClass,
  renderShieldsBadge,
  renderStatus,
  sortClassesByMissingFirst,
} from './shared';

export function generateGithubPlainComment(
  results: CoverageResult[],
  options: { threshold?: number } = {},
): string {
  const { threshold = 100 } = options;

  const total = results.length;
  const covered = results.filter(r => r.covered).length;
  const pct = total ? (covered / total) * 100 : 0;
  const passed = pct >= threshold;

  const badge = renderShieldsBadge(pct, passed);
  const grouped = groupByClass(results);

  const classLines = sortClassesByMissingFirst(grouped).map(cls => {
    const methods = [...grouped[cls]].sort((a, b) => {
      if (a.covered !== b.covered) return a.covered ? 1 : -1;
      return a.methodName.localeCompare(b.methodName);
    });
    const clsCovered = methods.filter(m => m.covered).length;
    const methodLines = methods
      .map(m => `  ${m.covered ? '[x]' : '[ ]'} ${m.methodName}`)
      .join('\n');
    return `**${cls}: ${clsCovered}/${methods.length}**\n${methodLines}`;
  }).join('\n\n');

  const status = renderStatus(pct, threshold, passed, 'plain');

  return [
    ``,
    `## 📊 API Coverage Report`,
    `\n`,
    `${badge}`,
    `\n`,
    `${status}`,
    `\n`,
    `<details>`,
    `<summary>🔍 View Detailed Coverage Breakdown</summary>`,
    `\n`,
    classLines,
    `\n`,
    `<sub>Plain report generated by \`@civitas-cerebrum/test-coverage\` · ${new Date().toISOString().slice(0, 10)}</sub>`,
    `</details>`,
  ].join('\n');
}

export function generateGithubTableComment(
  results: CoverageResult[],
  options: { threshold?: number } = {},
): string {
  const { threshold = 100 } = options;

  const total = results.length;
  const covered = results.filter(r => r.covered).length;
  const pct = total ? (covered / total) * 100 : 0;
  const passed = pct >= threshold;

  const badge = renderShieldsBadge(pct, passed);
  const grouped = groupByClass(results);

  const tableRows = sortClassesByMissingFirst(grouped).map(cls => {
    const methods = grouped[cls];
    const coveredMethods = methods.filter(m => m.covered).map(m => `\`${m.methodName}\``);
    const uncoveredMethods = methods.filter(m => !m.covered).map(m => `\`${m.methodName}\``);
    return `| **${cls}** | ${coveredMethods.length}/${methods.length} | ${uncoveredMethods.join(', ')} | ${coveredMethods.join(', ')} |`;
  }).join('\n');

  const status = renderStatus(pct, threshold, passed, 'emoji');

  return [
    ``,
    `## 📊 API Coverage Report`,
    `\n`,
    `${badge}`,
    `\n`,
    `| Category | Coverage | Missing Coverage ❌ | Covered Methods ✅ |`,
    `| :--- | :---: | :--- | :--- |`,
    tableRows,
    `\n`,
    `---`,
    `${status}`,
    `\n`,
    `<sub>Table report generated by \`@civitas-cerebrum/test-coverage\` · ${new Date().toISOString().slice(0, 10)}</sub>`,
  ].join('\n');
}
